import { describe, expect, it } from "vitest";
import { generateCompiledFileContent, resolveOutputPath } from "#src/cli/emitter.js";
import type { CodeGenResult } from "#src/core/codegen/index.js";

describe("generateCompiledFileContent()", () => {
  it("generates a valid compiled file with header", () => {
    const result: CodeGenResult = {
      code: "/* zod-aot */",
      functionName:
        'function safeParse_test(input){\nvar __issues=[];\nif(typeof input!=="string"){__issues.push({code:"invalid_type",expected:"string",received:typeof input,path:[],message:"Expected string"});}\nif(__issues.length>0)return{success:false,error:{issues:__issues}};\nreturn{success:true,data:input};\n}',
    };

    const content = generateCompiledFileContent(
      [{ exportName: "validateTest", codegenResult: result }],
      "./test.ts",
    );

    expect(content).toContain("// AUTO-GENERATED by zod-aot");
    expect(content).toContain("// Source: ./test.ts");
    expect(content).toContain("function safeParse_test(input)");
    expect(content).toContain("export const validateTest = {");
    expect(content).toContain("safeParse: safeParse_test,");
  });

  it("includes preamble declarations", () => {
    const result: CodeGenResult = {
      code: '/* zod-aot */\nconst __set_role_0 = new Set(["admin","user"]);',
      functionName: "function safeParse_role(input){\nreturn{success:true,data:input};\n}",
    };

    const content = generateCompiledFileContent(
      [{ exportName: "validateRole", codegenResult: result }],
      "./role.ts",
    );

    expect(content).toContain("/* zod-aot:preamble */");
    expect(content).toContain('const __set_role_0 = new Set(["admin","user"]);');
  });

  it("generates multiple schemas in one file", () => {
    const result1: CodeGenResult = {
      code: "/* zod-aot */",
      functionName: "function safeParse_a(input){\nreturn{success:true,data:input};\n}",
    };
    const result2: CodeGenResult = {
      code: "/* zod-aot */",
      functionName: "function safeParse_b(input){\nreturn{success:true,data:input};\n}",
    };

    const content = generateCompiledFileContent(
      [
        { exportName: "validateA", codegenResult: result1 },
        { exportName: "validateB", codegenResult: result2 },
      ],
      "./multi.ts",
    );

    expect(content).toContain("export const validateA = {");
    expect(content).toContain("export const validateB = {");
    expect(content).toContain("safeParse: safeParse_a,");
    expect(content).toContain("safeParse: safeParse_b,");
  });

  it("generated parse() throws on invalid input", () => {
    const result: CodeGenResult = {
      code: "/* zod-aot */",
      functionName:
        'function safeParse_num(input){\nvar __issues=[];\nif(typeof input!=="number"||input!==input){__issues.push({code:"invalid_type",expected:"number",received:typeof input,path:[],message:"Expected number"});}\nif(__issues.length>0)return{success:false,error:{issues:__issues}};\nreturn{success:true,data:input};\n}',
    };

    const content = generateCompiledFileContent(
      [{ exportName: "validateNum", codegenResult: result }],
      "./num.ts",
    );

    expect(content).toContain("throw Object.assign");
  });
});

describe("resolveOutputPath()", () => {
  it("defaults to .compiled.ts when no output flag", () => {
    const result = resolveOutputPath("src/schemas.ts", undefined);
    expect(result).toBe("src/schemas.compiled.ts");
  });

  it("uses output flag as-is when it's a file path", () => {
    const result = resolveOutputPath("src/schemas.ts", "out/validators.ts");
    expect(result).toBe("out/validators.ts");
  });

  it("puts compiled file inside directory when output ends with /", () => {
    const result = resolveOutputPath("src/schemas.ts", "out/");
    expect(result).toContain("out/");
    expect(result).toContain("schemas.compiled.ts");
  });
});
