import fs from "node:fs";
import path from "node:path";
import { generateIIFE, ZOD_CONFIG_IMPORT, ZOD_MSG_DECLARATION } from "#src/core/iife.js";
import type { CompiledSchemaInfo } from "#src/core/pipeline.js";

/**
 * Generate the content of a .compiled.ts file from multiple schemas.
 */
export interface EmitterOptions {
  /**
   * When true (default), uses Object.create for Zod-compatible output.
   * When false, produces a minimal plain object (smaller bundle).
   */
  zodCompat?: boolean | undefined;
}

export function generateCompiledFileContent(
  schemas: CompiledSchemaInfo[],
  sourceRelPath: string,
  options?: EmitterOptions,
): string {
  const importNames = schemas.map((s) => `${s.exportName} as __src_${s.exportName}`).join(", ");
  let importPath = sourceRelPath.replace(/\.[cm]?[jt]sx?$/, "");
  if (!importPath.startsWith(".")) {
    importPath = `./${importPath}`;
  }

  const zodCompat = options?.zodCompat !== false;
  const exports = schemas.map((schema) => {
    const schemaExpr = `(__src_${schema.exportName} as any).schema`;
    return `export const ${schema.exportName} = ${generateIIFE(schemaExpr, schema, { zodCompat })};`;
  });

  return [
    "// AUTO-GENERATED by zod-aot — DO NOT EDIT",
    `// Source: ${sourceRelPath}`,
    "",
    ZOD_CONFIG_IMPORT,
    ZOD_MSG_DECLARATION,
    "",
    `import { ${importNames} } from "${importPath}";`,
    "",
    ...exports,
    "",
  ].join("\n");
}

/**
 * Resolve the output file path for a given input file.
 */
export function resolveOutputPath(inputPath: string, outputFlag: string | undefined): string {
  if (outputFlag) {
    // If output flag ends with / or is a directory, put the compiled file inside it
    if (outputFlag.endsWith("/") || outputFlag.endsWith(path.sep)) {
      const baseName = path.basename(inputPath, path.extname(inputPath));
      return path.join(outputFlag, `${baseName}.compiled.ts`);
    }
    return outputFlag;
  }

  // Default: replace .ts with .compiled.ts
  const dir = path.dirname(inputPath);
  const baseName = path.basename(inputPath, path.extname(inputPath));
  return path.join(dir, `${baseName}.compiled.ts`);
}

/**
 * Write the compiled file content to disk.
 */
export async function writeCompiledFile(outputPath: string, content: string): Promise<void> {
  const dir = path.dirname(outputPath);
  await fs.promises.mkdir(dir, { recursive: true });
  await fs.promises.writeFile(outputPath, content, "utf-8");
}
