import fs from "node:fs";
import path from "node:path";
import { extractFunctionName } from "#src/core/codegen/context.js";
import type { CompiledSchemaInfo } from "#src/core/pipeline.js";

/**
 * Generate the content of a .compiled.ts file from multiple schemas.
 */
export function generateCompiledFileContent(
  schemas: CompiledSchemaInfo[],
  sourceRelPath: string,
): string {
  const lines: string[] = [];

  // Header
  lines.push("// AUTO-GENERATED by zod-aot — DO NOT EDIT");
  lines.push(`// Source: ${sourceRelPath}`);
  lines.push("");

  // Import original schemas for partial fallback (if any schema has fallbacks)
  const schemasWithFallbacks = schemas.filter((s) => s.fallbackEntries.length > 0);
  if (schemasWithFallbacks.length > 0) {
    const importPath = sourceRelPath.replace(/\.[cm]?[jt]sx?$/, "");
    const importNames = schemasWithFallbacks
      .map((s) => `${s.exportName} as __src_${s.exportName}`)
      .join(", ");
    lines.push(`import { ${importNames} } from "${importPath}";`);
    lines.push("");
  }

  // Fallback schema arrays
  for (const schema of schemasWithFallbacks) {
    const fbExprs = schema.fallbackEntries.map(
      (fb) => `(__src_${schema.exportName} as any).schema${fb.accessPath}`,
    );
    lines.push(`const __fb_${schema.exportName} = [${fbExprs.join(", ")}];`);
  }
  if (schemasWithFallbacks.length > 0) lines.push("");

  // Merge preambles — each schema's `code` field contains `/* zod-aot */` + preamble declarations
  const preambleSet = new Set<string>();
  for (const schema of schemas) {
    for (const line of schema.codegenResult.code.split("\n")) {
      if (line.trim() !== "" && line.trim() !== "/* zod-aot */") {
        preambleSet.add(line);
      }
    }
  }

  if (preambleSet.size > 0) {
    lines.push("/* zod-aot:preamble */");
    for (const line of preambleSet) {
      lines.push(line);
    }
    lines.push("");
  }

  // Function definitions
  for (const schema of schemas) {
    if (schema.fallbackEntries.length > 0) {
      // Inject __fb binding at function start
      const fnDef = schema.codegenResult.functionName;
      const injected = fnDef.replace(
        /^(function\s+\w+\(input\)\{)\n/,
        `$1\nvar __fb=__fb_${schema.exportName};\n`,
      );
      if (injected === fnDef) {
        throw new Error(
          `[zod-aot] Failed to inject __fb binding into ${schema.exportName}. ` +
            "Generated function format may have changed.",
        );
      }
      lines.push(injected);
    } else {
      lines.push(schema.codegenResult.functionName);
    }
    lines.push("");
  }

  // Export wrappers
  for (const schema of schemas) {
    const fnName = extractFunctionName(schema.codegenResult.functionName);
    lines.push(`export const ${schema.exportName} = {`);
    lines.push("  parse(input: unknown) {");
    lines.push(`    const r = ${fnName}(input);`);
    lines.push("    if (r.success) return r.data;");
    lines.push('    throw Object.assign(new Error("Validation failed"), r.error);');
    lines.push("  },");
    lines.push(`  safeParse: ${fnName},`);
    lines.push("  is(input: unknown): boolean {");
    lines.push(`    return ${fnName}(input).success;`);
    lines.push("  },");
    lines.push("};");
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Resolve the output file path for a given input file.
 */
export function resolveOutputPath(inputPath: string, outputFlag: string | undefined): string {
  if (outputFlag) {
    // If output flag ends with / or is a directory, put the compiled file inside it
    if (outputFlag.endsWith("/") || outputFlag.endsWith(path.sep)) {
      const baseName = path.basename(inputPath, path.extname(inputPath));
      return path.join(outputFlag, `${baseName}.compiled.ts`);
    }
    return outputFlag;
  }

  // Default: replace .ts with .compiled.ts
  const dir = path.dirname(inputPath);
  const baseName = path.basename(inputPath, path.extname(inputPath));
  return path.join(dir, `${baseName}.compiled.ts`);
}

/**
 * Write the compiled file content to disk.
 */
export async function writeCompiledFile(outputPath: string, content: string): Promise<void> {
  const dir = path.dirname(outputPath);
  await fs.promises.mkdir(dir, { recursive: true });
  await fs.promises.writeFile(outputPath, content, "utf-8");
}
